// Ideally, the types/configuration should be lazily read in from files or an API endpoint
// No source code changes should be necessary to add a new detector type (Resource Manager)
// Thinking 1 yaml file containing detector types with location of corresponding config files
// Types read in on load to populate selection menu. When a detector type is selected, the corresponding
// config file is lazily read in to populate the array/network selection menus and generate the sensor layout
// While initial detector loading may take some time, this is fine since rendering speed should not be impacted.

// There are some assumptions made in this file that may not be true for all detectors.
// 1. All arrays have the same number of networks
// 2. Network names are the same for each array
// 3. Unique network names can be generated by combining the array name and network name

// Should make this more network centric. User chooses which networks to view and then the arrays
// can be mostly aesthetic and appear when all the networks of a particular array are selected.

// TODO: Uncouple the hexagons from the detector type & sensors from the detector type. Sensors should probably
// be associated with a specific hexagon, but no need to associate hexagons with particular detectors. Detector
// layouts can customize the hexagon/networks based on the detector specs.
interface Component {
  arrayNames: string[];
  networkNames: string[];
}

// TODO: Default type of NONE or something that shows up as a placeholder? (choose detector type)
// TODO: Also not good that these names are duplicated in the sensor files.
// But don't want to require sensor data here since this is for populating the UI.
// Need to inject appropriate name into sensors when generating the layout.
export const componentMap: Record<string, Component> = {
  'BLAST': {
    arrayNames: ['BLAST Array'],
    networkNames: ['1'],
  },
  'PRIMECAM-280': {
    arrayNames: ['AL LEFT', 'AL RIGHT', 'TIN'],
    networkNames: ['1', '2', '3', '4', '5', '6'],
  },
}as const;

export const MAX_NETWORK_VALUES = Object.values(componentMap).reduce((max, config) => {
  const totalNetworks = config.arrayNames.length * config.networkNames.length;
  return Math.max(max, totalNetworks);
}, 0);

export const detectorOptions = Object.keys(componentMap).map((detectorType) => ({
  value: detectorType,
  label: detectorType,
}));

export const getDefaultDetectorType = (): string => 'BLAST';

export const getArraysForDetector = (type: string): string[] => {
  return componentMap[type].arrayNames;
};

// Bug here -> when an array is selected and then the detector type is changed, the selected arrays
// should be cleared (currently they are not). This results in the wrong networks being displayed until
// the user changes the selected arrays. Leaving for now in anticipation of reworking this to be more network centric.
export const getNetworksForDetectorArrays = (type: string, selectedArrays: string[]): string[] => {
  const config = componentMap[type];
  return Array.from(
    new Set(
      // Bug waiting to happen here with how networks names are generated -> see createHexagon
      // Network name should be the network name, not the array name + network name
      selectedArrays.flatMap((arrayName) => config.networkNames.map((networkName) => `${arrayName} ${networkName}`))
    )
  );
};
